name: stackoverflow_bert
channels:
  - conda-forge
  - pytorch  
  - defaults
dependencies:
  - python=3.9
  - pip
  - transformers
  - datasets
  - scikit-learn
  - pandas
  - pytorch  
  - pip:
      - pyyaml

