data_path: "./data/"
train_file: "stack_overflow_questions_train.csv"
valid_file: "stack_overflow_questions_valid.csv"
test_file: "stack_overflow_questions_test.csv"

model:
  pretrained_model: "bert-base-uncased"
  max_length: 128
  num_labels: 3
  batch_size: 16
  learning_rate: 0.0001
  epochs: 5
  eval_model: "finetuned" # Write "pretrained" if you want to evaluate the pretrained model

output_dir: "./models/bert_finetuned_stackoverflow/"
analyse_output: True # Change to False if you dont want to analyse the output
device: "cuda"  # Change to "cpu" if no GPU

